### ISSUE TITLE
개요 페이지 커서 모양 이미지로 변경

### ISSUE THREAD

**Issue by olsi10** [olsi10/starlight-promote#10]
![image](https://user-images.githubusercontent.com/87300199/191382122-446232ab-ccc2-4851-b99b-ea175616c7dd.png)

cursor : url(이미지), 좌표(x,y), 대체 커서 모양

지금 적용되지 않음.. ㅜ

**Comment by Hyemin-12** [comment]
커서 이미지 크기 조절해서 넣어야해요 
128px 이하만 적용됩미다
